# Generated by Django 5.0.3 on 2024-04-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
                ('type1', models.CharField(choices=[('Norm', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Elc', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fght', 'Fighting'), ('Poi', 'Poison'), ('Gro', 'Ground'), ('Fly', 'Flying'), ('Psy', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dra', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy'), ('Stel', 'Stellar'), ('Null', 'Null')], max_length=6)),
                ('type2', models.CharField(choices=[('Norm', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Elc', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fght', 'Fighting'), ('Poi', 'Poison'), ('Gro', 'Ground'), ('Fly', 'Flying'), ('Psy', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dra', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy'), ('Stel', 'Stellar'), ('Null', 'Null')], max_length=6)),
                ('sex', models.CharField(choices=[('Boy', 'Male'), ('Girl', 'Female')], max_length=6)),
                ('size_cm', models.IntegerField()),
                ('weight_lbs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phtos', to='main_app.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('Ber', 'Berries'), ('PokeB', 'Pokeblock'), ('Pof', 'Poffin'), ('Hon', 'Honey'), ('Apri', 'Aprijuice'), ('PokeP', 'Poke Puffs'), ('PokeBe', 'Poke Beans'), ('Cur', 'Curry'), ('Sand', 'Sandwiches'), ('Local', 'Local Specialty')])),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='main_app.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='main_app.user'),
        ),
    ]
