# Generated by Django 5.0.3 on 2024-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(choices=[('Norm', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy'), ('Stellar', 'Stellar'), ('Null', 'Null')]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(choices=[('Norm', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy'), ('Stellar', 'Stellar'), ('Null', 'Null')]),
        ),
    ]
