# Generated by Django 5.0.3 on 2024-04-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pokemon_species_alter_pokemon_type1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='species',
            field=models.CharField(max_length=13),
        ),
    ]
