# Generated by Django 5.0.3 on 2024-04-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pokemon_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('Berries', 'Berries'), ('PokeBlock', 'Pokeblock'), ('Poffin', 'Poffin'), ('Honey', 'Honey'), ('Aprijuice', 'Aprijuice'), ('PokePuffs', 'Poke Puffs'), ('PokeBeans', 'Poke Beans'), ('Curry', 'Curry'), ('Sandwich', 'Sandwiches'), ('Local', 'Local Specialty')]),
        ),
    ]
