# Generated by Django 5.0.3 on 2024-04-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_feeding_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
