# Generated by Django 5.0.3 on 2024-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_toy_email_toy_first_name_toy_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='N/A'),
            preserve_default=False,
        ),
    ]
